;METADATA=(Diff=true, UseCommands=true)
[CommonSettings]
SourcePath=Mods/GameFeatures/Silicon/Content/Localization/Silicon
DestinationPath=Mods/GameFeatures/Silicon/Content/Localization/Silicon
ManifestName=Silicon.manifest
ArchiveName=Silicon.archive
ResourceName=Silicon.locres
bSkipSourceCheck=false
bValidateFormatPatterns=true
bValidateSafeWhitespace=false
bValidateRichTextTags=false
NativeCulture=en
CulturesToGenerate=en
CulturesToGenerate=de
CulturesToGenerate=ja
CulturesToGenerate=ko
CulturesToGenerate=pl
CulturesToGenerate=ru
CulturesToGenerate=zh-CN

[GatherTextStep0]
CommandletClass=GenerateTextLocalizationResource

