;METADATA=(Diff=true, UseCommands=true)
[CommonSettings]
SourcePath=Saved/Tolgee/Temp/Silicon
DestinationPath=Mods/GameFeatures/Silicon/Content/Localization/Silicon
NativeCulture=en
CulturesToGenerate=en
CulturesToGenerate=de
CulturesToGenerate=ja
CulturesToGenerate=ko
CulturesToGenerate=pl
CulturesToGenerate=ru
CulturesToGenerate=zh
CulturesToGenerate=cs
CulturesToGenerate=es-ES
CulturesToGenerate=fr
CulturesToGenerate=hu
CulturesToGenerate=tr
CulturesToGenerate=uk
ManifestName=Silicon.manifest
ArchiveName=Silicon.archive
PortableObjectName=Silicon.po

[GatherTextStep0]
CommandletClass=InternationalizationExport
bImportLoc=true
LocalizedTextCollapseMode=ELocalizedTextCollapseMode::IdenticalTextIdAndSource
POFormat=EPortableObjectFormat::Crowdin

